name: Test Build Docker Image (Daily) on Ubuntu
on:
  pull_request:
    branches: [master]
    paths:
      - 'config/dockerfile/daily/**'
      - 'config/nvim/**'
      - 'config/zshrc/**'
      - 'script/linux/ubuntu/install_daily.sh'
      - 'script/linux/ubuntu/install_cmake.sh'
      - 'script/linux/ubuntu/install_fdfind.sh'
      - 'script/linux/ubuntu/install_lazygit.sh'
      - 'script/linux/ubuntu/install_nvim.sh'
      - 'script/linux/ubuntu/install_ripgrep.sh'
      - 'script/linux/ubuntu/install_zsh.sh'
      - 'script/linux/ubuntu/build_nvim.sh'
      - 'script/linux/ubuntu/build_clangd.sh'

jobs:
  build-amd64-docker:
    name: "Test Build Docker Images on Ubuntu-24.04 X86-64"
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # INFO: Should already set DOCKERHUB_TOKEN
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: emmettzhang
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: false
          context: config/dockerfile/daily/
          build-args: GIT_BRANCH=${{ github.event.pull_request.head.ref }}
          platforms: linux/amd64
          # cache-from: type=registry,ref=emmettzhang/github-build-cache:pull-request-amd64-build-cache
          # cache-to: type=registry,ref=emmettzhang/github-build-cache:pull-request-amd64-build-cache,mode=max

  build-arm64-docker:
    name: "Test Build Docker Images on Ubuntu-24.04 Arm"
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: emmettzhang
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: false
          context: config/dockerfile/daily/
          build-args: GIT_BRANCH=${{ github.event.pull_request.head.ref }}
          platforms: linux/arm64
          # cache-from: type=registry,ref=emmettzhang/github-build-cache:pull-request-arm64-build-cache
          # cache-to: type=registry,ref=emmettzhang/github-build-cache:pull-request-arm64-build-cache,mode=max

