name: Test Build Docker Images on Ubuntu
on:
  pull_request:
    branches: [master]
    paths:
      - 'config/dockerfile/daily/**'

jobs:
  build:
    name: "Test Build Docker Images on ${{ matrix.version }}"
    runs-on: ${{ matrix.version }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { version: "ubuntu-24.04" }

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ vars.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: false
          tags: user/app:latest
          context: config/dockerfile/daily/


