name: CI cpp-lint-action on Ubuntu 24.04
on:
  pull_request:
    branches: [master]
    paths:
      - 'bench/**'
      - 'demo/**'
      - 'tutorial/**'

jobs:
  build-tests:
    name: "cpp-lint-action"
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup Cpp
        uses: aminya/setup-cpp@v1
        with:
          clang-tidy: 20
          clang-format: 20
      - name: Run cpp-lint-action
        uses: emmett2020/cpp-lint-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          clang-format-version: 20
          enable-clang-tidy: false


