name: Pieces Coroutine Demo on Ubuntu 24.04
on:
  pull_request:
    branches: [master]
    paths: 'pieces/coroutine_demo/**'

jobs:
  build-unit-tests:
    name: "ubuntu-24.04-${{ matrix.compiler }}-${{ matrix.version }}"
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - { compiler: "gcc",   version: "14.2.0" }
          - { compiler: "clang", version: "18.1.3" }

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup C/C++ Environment
        run: |
          set -euo pipefail
          major=$(echo ${{ matrix.version }} | cut -d'.' -f1)
          if [[ "${{ matrix.compiler }}" == "clang" ]]; then
            echo "CC=clang-${major}" >> ${GITHUB_ENV}
            echo "CXX=clang++-${major}" >> ${GITHUB_ENV}
          else
            echo "CC=gcc-${major}" >> ${GITHUB_ENV}
            echo "CXX=g++-${major}" >> ${GITHUB_ENV}
          fi
      - name: Compile
        run: |
          set -euo pipefail
          sudo apt-get install -y ninja-build libboost-all-dev
          cd pieces/coroutine_demo/
          cmake -S . -B build -GNinja
          cmake --build build -v -j`nproc`
      - name: Run
        run: |
          cd pieces/coroutine_demo/

