name: CI Tutorial on Ubuntu 24.04
on:
  pull_request:
    branches: [master]
    paths: 'tutorial/**'

jobs:
  build-tests:
    name: "tutorial-ubuntu-24.04-${{ matrix.compiler }}-${{ matrix.version }}"
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - { compiler: "gcc",   version: "14.2.0" }
          - { compiler: "clang", version: "18.1.3" }

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup C/C++ Environment
        run: |
          set -euo pipefail
          major=$(echo ${{ matrix.version }} | cut -d'.' -f1)
          if [[ "${{ matrix.compiler }}" == "clang" ]]; then
            echo "CC=clang-${major}" >> ${GITHUB_ENV}
            echo "CXX=clang++-${major}" >> ${GITHUB_ENV}
          else
            echo "CC=gcc-${major}" >> ${GITHUB_ENV}
            echo "CXX=g++-${major}" >> ${GITHUB_ENV}
          fi
      - name: Setup Cpp
        uses: aminya/setup-cpp@v1
        with:
          clang-tidy: 20
          clang-format: 20
      - name: Install Common Dependency
        run: |
          sudo apt-get install -y ninja-build
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            design_pattern:
              - 'tutorial/design_pattern/**'
      - name: Compile And Run design_pattern
        run: |
          set -euo pipefail
          cd tutorial/design_pattern/
          cmake -S . -B build -GNinja
          cmake --build build -v -j`nproc`

      - name: Run cpp-lint-action on design_pattern
        if: steps.filter.outputs.design_pattern == 'true' && ${{ matrix.compiler }} == 'gcc'
        uses: emmett2020/cpp-lint-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          clang-format-version: 20
          enable-clang-tidy: false

