name: Nightly Build Docker Images Daily on Ubuntu

on:
  schedule:
    # Run daily at midnight UTC
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      tag:
        description: 'docker container tag'
        required: true
        default: '0.0.0'
        type: string

jobs:
  build-docker:
    name: "nightly-build-docker-images-daily-on-ubuntu-24.04"
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - { arch: "linux/amd64" }
          - { arch: "linux/arm64" }

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: emmettzhang
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Get Tag Name
        id: tag
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            tag="emmettzhang/daily:${{ inputs.tag }}"
          else
            timestamp=$(date +"%Y-%m-%d-%H-%M-%S")
            echo "timestamp: ${timestamp}"
            tag="emmettzhang/nightly:${timestamp}"
          fi
          echo "tag=${tag}" >> ${GITHUB_OUTPUT}

          arch=$(echo "${{ matrix.arch }}" | awk -F'/' '{print $2}')
          cache_tag="main-${arch}-build-cache"
          echo "cache_tag=${cache_tag}" >> ${GITHUB_OUTPUT}

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ steps.tag.outputs.tag }}
          context: config/dockerfile/daily/
          build-args: GIT_BRANCH=master
          platforms: ${{ matrix.arch }}
          cache-from: type=registry,ref=emmettzhang/github-build-cache:${{ steps.tag.outputs.cache_tag }}
          cache-to: type=registry,ref=emmettzhang/github-build-cache:${{ steps.tag.outputs.cache_tag }},mode=max
