name: Schedule Build Docker Images on Ubuntu

on:
  schedule:
    # Run daily at midnight UTC
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      tag:
        description: 'tag to deploy'
        required: true
        default: '0.0.0'
        type: string

jobs:
  build-docker:
    name: "schedule-build-docker-images-on-ubuntu-24.04"
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - { arch: "linux/amd64" }
          - { arch: "linux/arm64" }

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get Current Time
        id: time
        run: |
          timestamp=$(date +"%Y-%m-%d %H:%M:%S")
          echo ${timestamp}
          echo "timestamp=${timestamp}" >> ${GITHUB_OUTPUT}
      - name: Get Tag Name
        id: tag
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            tag="${{ inputs.tag }}"
            echo "tag=${tag}" >> ${GITHUB_OUTPUT}
          else
            tag="${{ steps.time.outputs.timestamp }}"
            echo "tag=${tag}" >> ${GITHUB_OUTPUT}
          fi
 
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: emmettzhang
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: emmettzhang/daily:${{ steps.tag.outputs.tag }}
          context: config/dockerfile/daily/
          build-args: GIT_BRANCH=main
          platforms: ${{ matrix.arch }}


